# Generated by Django 4.2 on 2023-05-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bus_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='type',
            new_name='bus_type',
        ),
    ]
