# Generated by Django 4.2 on 2023-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_type_bus_bus_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_type',
        ),
        migrations.AddField(
            model_name='bus',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
